name: TEMPLATE smoke tests
on:
  workflow_dispatch:

jobs:
  boost:
    name: TEMPLATE on ${{ matrix.target }} to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [juice-shop, dsvw, capital, brokencrystals]
        environment: [prod, dev]
        include:
          - environment: prod
            registry_url: https://github.com/boost-community/scanner-registry.git
            api_endpoint: https://api.boostsecurity.io
            api_token_secret_name: BOOST_API_KEY
          - environment: dev
            registry_url: https://github.com/boostsecurityio/dev-registry.git#TEMPLATE
            api_endpoint: https://api.dev.boostsec.io
            api_token_secret_name: BOOST_API_KEY_DEV
    steps:
      - name: Clone
        uses: actions/checkout@v3
      
      - name: 'TEMPLATE on ${{ matrix.target }}'
        continue-on-error: true
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/TEMPLATE
          api_endpoint: ${{ matrix.api_endpoint }}
          api_token: ${{ secrets[matrix.api_token_secret_name] }}
          scan_label: ${{ matrix.target }}
          scan_path: ${{ matrix.target }}
          log_level: INFO
        env:
          BOOST_SCANNER_REGISTRY_REPO: ${{ matrix.registry_url }}
          
